//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Relations {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosSQL() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EF_Relations.RecursosSQL", typeof(RecursosSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE SP_BORRA_PERSONAS_MENORES
        ///AS 
        ///BEGIN
        ///	SET NOCOUNT ON;
        ///	DELETE FROM PERSONAS 
        ///	WHERE EDAD &lt; 18
        ///
        ///END
        ///.
        /// </summary>
        internal static string C_SP_BORRA_PERSONAS_MENORES {
            get {
                return ResourceManager.GetString("C_SP_BORRA_PERSONAS_MENORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DROP PROCEDURE  SP_BORRA_PERSONAS_MENORES.
        /// </summary>
        internal static string D_SP_BORRA_PERSONAS_MENORES {
            get {
                return ResourceManager.GetString("D_SP_BORRA_PERSONAS_MENORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SP_BORRA_PERSONAS_MENORES.
        /// </summary>
        internal static string I_SP_BORRA_PERSONAS_MENORES {
            get {
                return ResourceManager.GetString("I_SP_BORRA_PERSONAS_MENORES", resourceCulture);
            }
        }
    }
}
